#!/bin/sh
 
echo ""
echo "🚀 Starting pre-commit checks..."
echo "-------------------------------"

echo "🔍 Running lint-staged..."
npx lint-staged

if [ $? -ne 0 ]; then
echo "❌ lint-staged checks failed."
echo "🚫 Commit aborted."
exit 1
fi

echo "✅ All checks passed!"
echo "✅ Commit allowed."
